Update gradlew

diff --git a/android/gradlew b/android/gradlew
--- a/android/gradlew
+++ b/android/gradlew
@@ -1,2 +1,46 @@
 #!/bin/sh
-exec sh "$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar" "$@"
+
+# Ensure safe execution environments
+DIRNAME=`dirname "$0"`
+APP_BASE_NAME=`basename "$0"`
+APP_HOME=`cd "$DIRNAME" && pwd`
+
+# Resolve links - $0 may be a softlink
+PRG="$0"
+while [ -h "$PRG" ] ; do
+    ls=`ls -ld "$PRG"`
+    link=`expr "$ls" : '.*-> \(.*\)$'`
+    if expr "$link" : '/.*' > /dev/null; then
+        PRG="$link"
+    else
+        PRG=`dirname "$PRG"`/"$link"
+    fi
+done
+SAVED="`pwd`"
+cd "`dirname \"$PRG\"`/" >/dev/null
+PRG="`basename \"$PRG\"`"
+APP_HOME="`pwd`"
+cd "$SAVED" >/dev/null
+
+CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
+
+# Determine the Java command to use
+if [ -n "$JAVA_HOME" ] ; then
+    if [ -x "$JAVA_HOME/bin/java" ] ; then
+        JAVACMD="$JAVA_HOME/bin/java"
+    else
+        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
+        echo "Please set the JAVA_HOME variable in your environment to match the location of your Java installation." >&2
+        exit 1
+    fi
+else
+    JAVACMD="java"
+    which java >/dev/null 2>&1 || {
+        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
+        echo "Please set the JAVA_HOME variable in your environment to match the location of your Java installation." >&2
+        exit 1
+    }
+fi
+
+# Execute Gradle
+exec "$JAVACMD" "-Xmx64m" "-Xms64m" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
